# Generated by Django 5.1.6 on 2025-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description_short", models.TextField()),
                ("description_long", models.TextField()),
                ("imgs", models.ImageField(upload_to="")),
            ],
        ),
    ]
