# Generated by Django 5.1.6 on 2025-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Places",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                (
                    "description_short",
                    models.TextField(blank=True, verbose_name="краткое описание"),
                ),
                ("description_long", models.TextField(verbose_name="полное описание")),
                (
                    "imgs",
                    models.ImageField(upload_to="", verbose_name="список картинок"),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=20, max_digits=50, verbose_name="широта"
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        decimal_places=20, max_digits=50, verbose_name="долгота"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Place",
        ),
    ]
