# Generated by Django 5.1.6 on 2025-09-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_places_delete_place"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Places",
            new_name="Place",
        ),
    ]
