# Generated by Django 5.1.6 on 2025-09-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_rename_places_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="imgs",
        ),
    ]
