# Generated by Django 5.1.6 on 2025-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_remove_place_imgs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="название картинки"),
                ),
                ("img", models.ImageField(upload_to="", verbose_name="картинка")),
            ],
        ),
    ]
