# Generated by Django 5.1.6 on 2025-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="index",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="индекс картинки"
            ),
        ),
    ]
