# Generated by Django 5.1.6 on 2025-09-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_image_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imgs",
                to="places.place",
                verbose_name="место",
            ),
        ),
    ]
