# Generated by Django 5.1.6 on 2025-10-04 16:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_image_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["index"]},
        ),
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="полное описание"),
        ),
    ]
