# Generated by Django 5.1.6 on 2025-10-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_alter_image_options_alter_place_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="название"
            ),
        ),
    ]
