# Generated by Django 5.1.6 on 2025-10-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_alter_place_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="description_long",
            new_name="long_description",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description_short",
            new_name="short_description",
        ),
    ]
