# Generated by Django 5.1.6 on 2025-10-11 15:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_rename_description_long_place_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="long_description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="полное описание"),
        ),
    ]
