# Generated by Django 5.1.6 on 2025-10-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_alter_place_long_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imgs",
                to="places.place",
                verbose_name="место",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="название картинки"
            ),
        ),
    ]
