# Generated by Django 5.1.6 on 2025-10-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0012_alter_image_place_alter_image_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
