# Generated by Django 5.1.6 on 2025-10-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0014_alter_image_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="place",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imgs",
                to="places.place",
                verbose_name="место",
            ),
            preserve_default=False,
        ),
    ]
