# Generated by Django 5.1.6 on 2025-10-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0015_alter_image_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="title",
        ),
    ]
